import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/auth/login.tsx"),
  route("register", "routes/auth/register.tsx"),
  route("logout", "routes/auth/logout.tsx"),
  route("auth/google", "routes/auth/google.tsx"),
  route("auth/google/callback", "routes/auth/google-callback.tsx"),
  route("productos", "routes/products/catalog.tsx"),
  route("productos/:slug", "routes/products/detail.tsx"),
  route("categoria/:slug", "routes/products/category.tsx"),
  route("buscar", "routes/products/search.tsx"),
  route("carrito", "routes/cart/view.tsx"),
  route("checkout", "routes/cart/checkout.tsx"),
  route("cuenta", "routes/account/dashboard.tsx"),
  route("cuenta/pedidos", "routes/account/orders.tsx"),
  route("cuenta/perfil", "routes/account/profile.tsx"),
  route("cuenta/direcciones", "routes/account/addresses.tsx"),
  route("admin", "routes/admin/dashboard.tsx"),
  route("admin/productos", "routes/admin/products.tsx"),
  route("admin/productos/nuevo", "routes/admin/product-new.tsx"),
  route("admin/productos/:id/editar", "routes/admin/product-edit.tsx"),
  route("admin/categorias", "routes/admin/categories.tsx"),
  route("admin/pedidos", "routes/admin/orders.tsx"),
  route("admin/usuarios", "routes/admin/users.tsx"),
  route("admin/resenas", "routes/admin/reviews.tsx"),
  route("admin/roles", "routes/admin/roles.tsx"),
  route("admin/auditoria", "routes/admin/audit-log.tsx"),
  route("api/cart/add", "routes/api/cart-add.tsx"),
  route("api/cart/update", "routes/api/cart-update.tsx"),
  route("api/cart/remove", "routes/api/cart-remove.tsx"),
] satisfies RouteConfig;
