import { redirect } from "react-router";
import type { Route } from "./+types/addresses";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getAddressesByUser, createAddress, deleteAddress } from "~/lib/db/queries";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); const addresses = await getAddressesByUser(env.DB, appContext.user.id); return { appContext, addresses }; };
export function meta() { return [{ title: "Direcciones — TiendaOnline" }]; }
export async function action({ request, context }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); const formData = await request.formData(); const action = formData.get("action") as string; if (action === "add") { await createAddress(env.DB, { userId: appContext.user.id, fullName: formData.get("fullName") as string, phone: formData.get("phone") as string, line1: formData.get("line1") as string, line2: formData.get("line2") as string, city: formData.get("city") as string, state: formData.get("state") as string, postalCode: formData.get("postalCode") as string, country: "ES", isDefault: formData.get("isDefault") === "on" }); return { success: "Añadida" }; } if (action === "delete") { await deleteAddress(env.DB, parseInt(formData.get("id") as string)); return { success: "Eliminada" }; } return null; }
export default function Addresses({ loaderData, actionData }: Route.ComponentProps) {
  const { addresses } = loaderData;
  return (<div className="container-app py-8 max-w-2xl"><h1 className="text-2xl font-bold mb-6">Mis direcciones</h1>{actionData?.success && <div className="bg-green-50 border border-green-200 text-green-700 rounded-lg p-3 text-sm mb-4">{actionData.success}</div>}<div className="space-y-3 mb-6">{addresses.length === 0 ? <p className="text-muted text-sm">Sin direcciones.</p> : addresses.map((a) => <div key={a.id} className="card p-4"><div className="flex justify-between"><div><p className="font-medium text-sm">{a.full_name}</p><p className="text-sm text-muted">{a.line1}, {a.city}</p></div><form method="post"><input type="hidden" name="action" value="delete" /><input type="hidden" name="id" value={a.id} /><button type="submit" className="text-sm text-red-500">Eliminar</button></form></div></div>)}</div><div className="card p-6"><h2 className="font-bold mb-4">Nueva dirección</h2><form method="post" className="space-y-4"><input type="hidden" name="action" value="add" /><div><label className="text-sm font-medium block mb-1">Nombre</label><input type="text" name="fullName" required className="input" /></div><div><label className="text-sm font-medium block mb-1">Dirección</label><input type="text" name="line1" required className="input" /></div><div><label className="text-sm font-medium block mb-1">Ciudad</label><input type="text" name="city" required className="input" /></div><div><label className="text-sm font-medium block mb-1">Código postal</label><input type="text" name="postalCode" className="input" /></div><button type="submit" className="btn-primary">Añadir</button></form></div></div>);
}
