import { Link, redirect } from "react-router";
import type { Route } from "./+types/dashboard";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getOrdersByUser } from "~/lib/db/queries";
import { formatPrice, formatDateTime } from "~/lib/utils";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); const orders = await getOrdersByUser(env.DB, appContext.user.id); return { appContext, orders }; };
export function meta() { return [{ title: "Mi cuenta — TiendaOnline" }]; }
export default function AccountDashboard({ loaderData }: Route.ComponentProps) {
  const { user, orders } = loaderData.appContext;
  return (<div className="container-app py-8"><h1 className="text-2xl font-bold mb-6">Mi cuenta</h1><div className="card p-6 mb-6 flex items-center gap-4"><span className="h-16 w-16 rounded-full bg-brand-100 text-brand-700 flex items-center justify-center text-2xl font-bold">{user!.name.charAt(0).toUpperCase()}</span><div><h2 className="font-bold text-lg">{user!.name}</h2><p className="text-sm text-muted">{user!.email}</p></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8"><Link to="/cuenta/pedidos" className="card p-4 text-center hover:shadow-lg"><span className="text-3xl block mb-1">📦</span><p className="text-sm font-medium">Pedidos</p></Link><Link to="/cuenta/perfil" className="card p-4 text-center hover:shadow-lg"><span className="text-3xl block mb-1">⚙️</span><p className="text-sm font-medium">Perfil</p></Link><Link to="/cuenta/direcciones" className="card p-4 text-center hover:shadow-lg"><span className="text-3xl block mb-1">📍</span><p className="text-sm font-medium">Direcciones</p></Link><Link to="/carrito" className="card p-4 text-center hover:shadow-lg"><span className="text-3xl block mb-1">🛒</span><p className="text-sm font-medium">Carrito</p></Link></div><div className="card p-6"><h2 className="font-bold mb-4">Pedidos recientes</h2>{orders.length === 0 ? <p className="text-muted text-sm">Sin pedidos.</p> : <div className="space-y-3">{orders.slice(0, 5).map((o) => <div key={o.id} className="flex items-center justify-between border-b border-border pb-3 last:border-0"><div><p className="font-medium text-sm">{o.order_number}</p><p className="text-xs text-muted">{formatDateTime(o.created_at)}</p></div><span className="badge bg-yellow-100 text-yellow-700">{o.status}</span><span className="font-bold text-sm">{formatPrice(o.total)}</span></div>)}</div>}</div></div>);
}
