import { redirect } from "react-router";
import type { Route } from "./+types/profile";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { hashPassword, verifyPassword } from "~/lib/auth";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); return { appContext }; };
export function meta() { return [{ title: "Perfil — TiendaOnline" }]; }
export async function action({ request, context }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); const formData = await request.formData(); const action = formData.get("action") as string; if (action === "updateProfile") { await env.DB.prepare("UPDATE users SET name = ?, updated_at = datetime('now') WHERE id = ?").bind(formData.get("name") as string, appContext.user.id).run(); return { success: "Perfil actualizado" }; } if (action === "changePassword") { const currentPassword = formData.get("currentPassword") as string; const newPassword = formData.get("newPassword") as string; const user = await env.DB.prepare("SELECT password_hash FROM users WHERE id = ?").bind(appContext.user.id).first<{ password_hash: string }>(); if (user?.password_hash) { const valid = await verifyPassword(currentPassword, user.password_hash); if (!valid) return { error: "Contraseña incorrecta" }; } if (newPassword.length < 6) return { error: "Mínimo 6 caracteres" }; const newHash = await hashPassword(newPassword); await env.DB.prepare("UPDATE users SET password_hash = ?, updated_at = datetime('now') WHERE id = ?").bind(newHash, appContext.user.id).run(); return { success: "Contraseña cambiada" }; } return null; }
export default function Profile({ loaderData, actionData }: Route.ComponentProps) {
  const { user } = loaderData.appContext;
  return (<div className="container-app py-8 max-w-2xl"><h1 className="text-2xl font-bold mb-6">Mi perfil</h1>{actionData?.error && <div className="bg-red-50 border border-red-200 text-red-700 rounded-lg p-3 text-sm mb-4">{actionData.error}</div>}{actionData?.success && <div className="bg-green-50 border border-green-200 text-green-700 rounded-lg p-3 text-sm mb-4">{actionData.success}</div>}<div className="card p-6 mb-6"><h2 className="font-bold mb-4">Info personal</h2><form method="post" className="space-y-4"><input type="hidden" name="action" value="updateProfile" /><div><label className="text-sm font-medium block mb-1">Nombre</label><input type="text" name="name" defaultValue={user!.name} className="input" /></div><div><label className="text-sm font-medium block mb-1">Email</label><input type="email" value={user!.email} disabled className="input bg-muted/10" /></div><button type="submit" className="btn-primary">Guardar</button></form></div>{user!.password_hash !== null && <div className="card p-6"><h2 className="font-bold mb-4">Cambiar contraseña</h2><form method="post" className="space-y-4"><input type="hidden" name="action" value="changePassword" /><div><label className="text-sm font-medium block mb-1">Actual</label><input type="password" name="currentPassword" required className="input" /></div><div><label className="text-sm font-medium block mb-1">Nueva</label><input type="password" name="newPassword" required className="input" /></div><button type="submit" className="btn-primary">Cambiar</button></form></div>}</div>);
}
