import { redirect } from "react-router";
import type { Route } from "./+types/categories";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getAllCategories, createCategory, deleteCategory, createAuditLog } from "~/lib/db/queries";
import { canAccessAdmin } from "~/lib/roles";
import { AdminLayout } from "~/components/admin/AdminLayout";
import { slugify } from "~/lib/utils";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); if (!canAccessAdmin(appContext.user as never)) return redirect("/"); const categories = await getAllCategories(env.DB); return { appContext, categories }; };
export function meta() { return [{ title: "Categorías — Admin" }]; }
export async function action({ request, context }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user || !canAccessAdmin(appContext.user as never)) return redirect("/"); const formData = await request.formData(); const action = formData.get("action") as string; if (action === "create") { const name = formData.get("name") as string; await createCategory(env.DB, { name, slug: slugify(name), parentId: formData.get("parentId") ? parseInt(formData.get("parentId") as string) : null, icon: formData.get("icon") as string }); return { success: "Creada" }; } if (action === "delete") { await deleteCategory(env.DB, parseInt(formData.get("id") as string)); return { success: "Eliminada" }; } return null; }
export default function AdminCategories({ loaderData, actionData }: Route.ComponentProps) { const { user, categories } = loaderData; const top = categories.filter((c) => c.parent_id === null); return <AdminLayout user={user!} activeSection="categories"><div><h1 className="text-2xl font-bold mb-6">Categorías</h1>{actionData?.success && <div className="bg-green-50 border border-green-200 text-green-700 rounded-lg p-3 text-sm mb-4">{actionData.success}</div>}<div className="grid lg:grid-cols-2 gap-6"><div className="space-y-3">{top.map((cat) => { const subs = categories.filter((c) => c.parent_id === cat.id); return <div key={cat.id} className="card p-4"><div className="flex justify-between"><span>{cat.icon ?? "📁"} {cat.name}</span><form method="post" onSubmit={(e) => { if (!confirm("¿Eliminar?")) e.preventDefault(); }}><input type="hidden" name="action" value="delete" /><input type="hidden" name="id" value={cat.id} /><button type="submit" className="text-red-500 text-xs">Eliminar</button></form></div>{subs.length > 0 && <div className="mt-2 ml-6">{subs.map((s) => <div key={s.id} className="flex justify-between text-sm"><span>{s.icon ?? "📁"} {s.name}</span><form method="post" onSubmit={(e) => { if (!confirm("¿Eliminar?")) e.preventDefault(); }}><input type="hidden" name="action" value="delete" /><input type="hidden" name="id" value={s.id} /><button type="submit" className="text-red-500 text-xs">Eliminar</button></form></div>)}</div>}</div>; })}</div><div className="card p-6 h-fit"><h2 className="font-bold mb-4">Nueva</h2><form method="post" className="space-y-4"><input type="hidden" name="action" value="create" /><div><label className="text-sm font-medium block mb-1">Nombre</label><input type="text" name="name" required className="input" /></div><div><label className="text-sm font-medium block mb-1">Icono</label><input type="text" name="icon" placeholder="📦" className="input" /></div><div><label className="text-sm font-medium block mb-1">Padre</label><select name="parentId" className="input"><option value="">Principal</option>{top.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div><button type="submit" className="btn-primary">Crear</button></form></div></div></div></AdminLayout>; }
