import { redirect } from "react-router";
import type { Route } from "./+types/orders";
import type { Env, OrderStatus } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getAllOrders, updateOrderStatus, createAuditLog } from "~/lib/db/queries";
import { canAccessAdmin } from "~/lib/roles";
import { AdminLayout } from "~/components/admin/AdminLayout";
import { formatPrice, formatDateTime } from "~/lib/utils";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); if (!canAccessAdmin(appContext.user as never)) return redirect("/"); const url = new URL(request.url); const page = parseInt(url.searchParams.get("page") ?? "1"); const orders = await getAllOrders(env.DB, page, 20); return { appContext, orders }; };
export function meta() { return [{ title: "Pedidos — Admin" }]; }
export async function action({ request, context }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user || !canAccessAdmin(appContext.user as never)) return redirect("/"); const formData = await request.formData(); const id = parseInt(formData.get("id") as string); const status = formData.get("status") as OrderStatus; await updateOrderStatus(env.DB, id, status); await createAuditLog(env.DB, { userId: appContext.user.id, action: "order_status_updated", entityType: "order", entityId: id }); return { success: "Actualizado" }; }
export default function AdminOrders({ loaderData, actionData }: Route.ComponentProps) { const { user, orders } = loaderData; return <AdminLayout user={user!} activeSection="orders"><div><h1 className="text-2xl font-bold mb-6">Pedidos ({orders.total})</h1>{actionData?.success && <div className="bg-green-50 border border-green-200 text-green-700 rounded-lg p-3 text-sm mb-4">{actionData.success}</div>}<div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-border"><tr className="text-left text-muted"><th className="p-3">Nº</th><th className="p-3">Fecha</th><th className="p-3">Total</th><th className="p-3">Estado</th><th className="p-3">Cambiar</th></tr></thead><tbody>{orders.items.map((o) => <tr key={o.id} className="border-b border-border last:border-0"><td className="p-3 font-medium">{o.order_number}</td><td className="p-3 text-muted">{formatDateTime(o.created_at)}</td><td className="p-3 font-bold">{formatPrice(o.total)}</td><td className="p-3"><span className="badge bg-yellow-100 text-yellow-700">{o.status}</span></td><td className="p-3"><form method="post" className="flex gap-2"><input type="hidden" name="id" value={o.id} /><select name="status" defaultValue={o.status} className="input h-8 py-0 text-xs"><option value="pending">Pendiente</option><option value="paid">Pagado</option><option value="shipped">Enviado</option><option value="delivered">Entregado</option><option value="cancelled">Cancelado</option></select><button type="submit" className="btn-primary h-8 px-3 text-xs">OK</button></form></td></tr>)}</tbody></table></div></div></AdminLayout>; }
