import { redirect } from "react-router";
import { Link } from "react-router";
import type { Route } from "./+types/product-new";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { createProduct, getAllCategories, createAuditLog } from "~/lib/db/queries";
import { canAccessAdmin } from "~/lib/roles";
import { AdminLayout } from "~/components/admin/AdminLayout";
import { slugify } from "~/lib/utils";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); if (!canAccessAdmin(appContext.user as never)) return redirect("/"); const categories = await getAllCategories(env.DB); return { appContext, categories }; };
export function meta() { return [{ title: "Nuevo producto — Admin" }]; }
export async function action({ request, context }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user || !canAccessAdmin(appContext.user as never)) return redirect("/"); const formData = await request.formData(); const name = formData.get("name") as string; const id = await createProduct(env.DB, { name, slug: slugify(name), description: formData.get("description") as string, price: parseFloat(formData.get("price") as string), comparePrice: formData.get("comparePrice") ? parseFloat(formData.get("comparePrice") as string) : null, stock: parseInt(formData.get("stock") as string), categoryId: formData.get("categoryId") ? parseInt(formData.get("categoryId") as string) : null, isFeatured: formData.get("isFeatured") === "on" }); await createAuditLog(env.DB, { userId: appContext.user.id, action: "product_created", entityType: "product", entityId: id }); return redirect("/admin/productos"); }
export default function AdminProductNew({ loaderData }: Route.ComponentProps) { const { user, categories } = loaderData; return <AdminLayout user={user!} activeSection="products"><div><div className="flex items-center gap-4 mb-6"><Link to="/admin/productos" className="btn-ghost">←</Link><h1 className="text-2xl font-bold">Nuevo producto</h1></div><div className="card p-6 max-w-2xl"><form method="post" className="space-y-4"><div><label className="text-sm font-medium block mb-1">Nombre</label><input type="text" name="name" required className="input" /></div><div><label className="text-sm font-medium block mb-1">Descripción</label><textarea name="description" rows={4} className="input" /></div><div className="grid grid-cols-2 gap-4"><div><label className="text-sm font-medium block mb-1">Precio (€)</label><input type="number" name="price" step="0.01" required className="input" /></div><div><label className="text-sm font-medium block mb-1">Comparación (€)</label><input type="number" name="comparePrice" step="0.01" className="input" /></div></div><div className="grid grid-cols-2 gap-4"><div><label className="text-sm font-medium block mb-1">Stock</label><input type="number" name="stock" defaultValue="0" required className="input" /></div><div><label className="text-sm font-medium block mb-1">Categoría</label><select name="categoryId" className="input"><option value="">Sin categoría</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isFeatured" /> Destacado</label><button type="submit" className="btn-primary">Crear</button></form></div></div></AdminLayout>; }
