import { redirect } from "react-router";
import { Link } from "react-router";
import type { Route } from "./+types/product-edit";
import type { Env, Product } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getAllCategories, updateProduct, createAuditLog } from "~/lib/db/queries";
import { canAccessAdmin } from "~/lib/roles";
import { AdminLayout } from "~/components/admin/AdminLayout";
export const loader = async ({ request, context, params }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); if (!canAccessAdmin(appContext.user as never)) return redirect("/"); const product = await env.DB.prepare("SELECT * FROM products WHERE id = ?").bind(params.id).first<Product>(); if (!product) throw new Response("No encontrado", { status: 404 }); const categories = await getAllCategories(env.DB); return { appContext, product, categories }; };
export function meta() { return [{ title: "Editar — Admin" }]; }
export async function action({ request, context, params }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user || !canAccessAdmin(appContext.user as never)) return redirect("/"); const formData = await request.formData(); const id = parseInt(params.id); await updateProduct(env.DB, id, { name: formData.get("name") as string, description: formData.get("description") as string, price: parseFloat(formData.get("price") as string), compare_price: formData.get("comparePrice") ? parseFloat(formData.get("comparePrice") as string) : null, stock: parseInt(formData.get("stock") as string), category_id: formData.get("categoryId") ? parseInt(formData.get("categoryId") as string) : null, is_active: formData.get("isActive") === "on" ? 1 : 0, is_featured: formData.get("isFeatured") === "on" ? 1 : 0 }); await createAuditLog(env.DB, { userId: appContext.user.id, action: "product_updated", entityType: "product", entityId: id }); return redirect("/admin/productos"); }
export default function AdminProductEdit({ loaderData }: Route.ComponentProps) { const { user, product, categories } = loaderData; return <AdminLayout user={user!} activeSection="products"><div><div className="flex items-center gap-4 mb-6"><Link to="/admin/productos" className="btn-ghost">←</Link><h1 className="text-2xl font-bold">Editar producto</h1></div><div className="card p-6 max-w-2xl"><form method="post" className="space-y-4"><div><label className="text-sm font-medium block mb-1">Nombre</label><input type="text" name="name" defaultValue={product.name} required className="input" /></div><div><label className="text-sm font-medium block mb-1">Descripción</label><textarea name="description" rows={4} defaultValue={product.description ?? ""} className="input" /></div><div className="grid grid-cols-2 gap-4"><div><label className="text-sm font-medium block mb-1">Precio (€)</label><input type="number" name="price" step="0.01" defaultValue={product.price} required className="input" /></div><div><label className="text-sm font-medium block mb-1">Comparación (€)</label><input type="number" name="comparePrice" step="0.01" defaultValue={product.compare_price ?? ""} className="input" /></div></div><div className="grid grid-cols-2 gap-4"><div><label className="text-sm font-medium block mb-1">Stock</label><input type="number" name="stock" defaultValue={product.stock} required className="input" /></div><div><label className="text-sm font-medium block mb-1">Categoría</label><select name="categoryId" defaultValue={product.category_id ?? ""} className="input"><option value="">Sin categoría</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div><div className="flex gap-6"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked={product.is_active === 1} /> Activo</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isFeatured" defaultChecked={product.is_featured === 1} /> Destacado</label></div><button type="submit" className="btn-primary">Guardar</button></form></div></div></AdminLayout>; }
