import { redirect } from "react-router";
import { Link } from "react-router";
import type { Route } from "./+types/products";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getAllProducts, deleteProduct, createAuditLog } from "~/lib/db/queries";
import { canAccessAdmin } from "~/lib/roles";
import { AdminLayout } from "~/components/admin/AdminLayout";
import { formatPrice } from "~/lib/utils";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); if (!canAccessAdmin(appContext.user as never)) return redirect("/"); const url = new URL(request.url); const page = parseInt(url.searchParams.get("page") ?? "1"); const products = await getAllProducts(env.DB, page, 20); return { appContext, products }; };
export function meta() { return [{ title: "Productos — Admin" }]; }
export async function action({ request, context }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user || !canAccessAdmin(appContext.user as never)) return redirect("/"); const formData = await request.formData(); const id = parseInt(formData.get("id") as string); await deleteProduct(env.DB, id); await createAuditLog(env.DB, { userId: appContext.user.id, action: "product_deleted", entityType: "product", entityId: id }); return { success: "Eliminado" }; }
export default function AdminProducts({ loaderData }: Route.ComponentProps) { const { user } = loaderData.appContext; const { products } = loaderData; return <AdminLayout user={user!} activeSection="products"><div><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold">Productos ({products.total})</h1><Link to="/admin/productos/nuevo" className="btn-primary">+ Nuevo</Link></div><div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-border"><tr className="text-left text-muted"><th className="p-3">Nombre</th><th className="p-3">Precio</th><th className="p-3">Stock</th><th className="p-3">Estado</th><th className="p-3">Acciones</th></tr></thead><tbody>{products.items.map((p) => <tr key={p.id} className="border-b border-border last:border-0"><td className="p-3 font-medium">{p.name}</td><td className="p-3">{formatPrice(p.price)}</td><td className="p-3">{p.stock}</td><td className="p-3"><span className={"badge " + p.is_active === 1 ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"}>{p.is_active === 1 ? "Activo" : "Inactivo"}</span></td><td className="p-3"><Link to={"/admin/productos/" + p.id + "/editar"} className="text-brand-600 text-xs">Editar</Link><form method="post" className="inline" onSubmit={(e) => { if (!confirm("¿Eliminar?")) e.preventDefault(); }}><input type="hidden" name="id" value={p.id} /><button type="submit" className="text-red-500 text-xs ml-2">Eliminar</button></form></td></tr>)}</tbody></table></div></div></AdminLayout>; }
