import { redirect } from "react-router";
import type { Route } from "./+types/reviews";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getPendingReviews, approveReview, deleteReview, createAuditLog } from "~/lib/db/queries";
import { canAccessAdmin } from "~/lib/roles";
import { AdminLayout } from "~/components/admin/AdminLayout";
import { formatDateTime, renderStars } from "~/lib/utils";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); if (!canAccessAdmin(appContext.user as never)) return redirect("/"); const reviews = await getPendingReviews(env.DB); return { appContext, reviews }; };
export function meta() { return [{ title: "Reseñas — Admin" }]; }
export async function action({ request, context }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user || !canAccessAdmin(appContext.user as never)) return redirect("/"); const formData = await request.formData(); const id = parseInt(formData.get("id") as string); const action = formData.get("action") as string; if (action === "approve") { await approveReview(env.DB, id); return { success: "Aprobada" }; } if (action === "delete") { await deleteReview(env.DB, id); return { success: "Eliminada" }; } return null; }
export default function AdminReviews({ loaderData, actionData }: Route.ComponentProps) { const { user, reviews } = loaderData; return <AdminLayout user={user!} activeSection="reviews"><div><h1 className="text-2xl font-bold mb-6">Reseñas pendientes ({reviews.length})</h1>{actionData?.success && <div className="bg-green-50 border border-green-200 text-green-700 rounded-lg p-3 text-sm mb-4">{actionData.success}</div>}{reviews.length === 0 ? <div className="card p-8 text-center"><p className="text-muted">Sin reseñas pendientes.</p></div> : <div className="space-y-3">{reviews.map((r) => <div key={r.id} className="card p-4"><div className="flex justify-between mb-2"><div><p className="font-medium text-sm">{(r as any).name ?? "Usuario"}</p><p className="text-xs text-muted">{formatDateTime(r.created_at)}</p></div><span className="text-sm">{renderStars(r.rating)}</span></div>{r.comment && <p className="text-sm text-muted mb-3">{r.comment}</p>}<div className="flex gap-2"><form method="post"><input type="hidden" name="action" value="approve" /><input type="hidden" name="id" value={r.id} /><button type="submit" className="btn-primary text-xs px-3 py-1">Aprobar</button></form><form method="post"><input type="hidden" name="action" value="delete" /><input type="hidden" name="id" value={r.id} /><button type="submit" className="btn-secondary text-xs px-3 py-1 text-red-600">Rechazar</button></form></div></div>)}</div>}</div></AdminLayout>; }
