import { redirect } from "react-router";
import type { Route } from "./+types/roles";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getAllRoles } from "~/lib/db/queries";
import { isSuperAdmin, PERMISSIONS } from "~/lib/roles";
import { AdminLayout } from "~/components/admin/AdminLayout";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); if (!isSuperAdmin(appContext.user as never)) return redirect("/admin"); const roles = await getAllRoles(env.DB); return { appContext, roles }; };
export function meta() { return [{ title: "Roles — Admin" }]; }
export default function AdminRoles({ loaderData }: Route.ComponentProps) { const { user, roles } = loaderData; return <AdminLayout user={user!} activeSection="roles"><div><h1 className="text-2xl font-bold mb-6">Roles y permisos</h1><div className="card p-6 mb-6"><h2 className="font-bold mb-4">Jerarquía</h2><div className="space-y-3">{roles.map((r) => <div key={r.id} className="flex items-center gap-4 border-b border-border pb-3 last:border-0"><span className="badge bg-brand-50 text-brand-700 font-mono">{r.level}</span><div><p className="font-medium capitalize">{r.name.replace("_", " ")}</p><p className="text-xs text-muted">{r.description}</p></div></div>)}</div></div><div className="card p-6 overflow-x-auto"><h2 className="font-bold mb-4">Permisos</h2><table className="w-full text-sm"><thead className="border-b border-border"><tr className="text-left text-muted"><th className="p-2">Permiso</th>{roles.map((r) => <th key={r.id} className="p-2 text-center capitalize">{r.name.replace("_", " ")}</th>)}</tr></thead><tbody>{Object.entries(PERMISSIONS).map(([perm, allowed]) => <tr key={perm} className="border-b border-border last:border-0"><td className="p-2 font-mono text-xs">{perm}</td>{roles.map((r) => <td key={r.id} className="p-2 text-center">{(allowed as readonly string[]).includes(r.name) ? <span className="text-green-600">✅</span> : <span className="text-muted">—</span>}</td>)}</tr>)}</tbody></table></div></div></AdminLayout>; }
