import { redirect } from "react-router";
import type { Route } from "./+types/users";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getAllUsers, getAllRoles, updateUserRole, updateUserStatus, createAuditLog } from "~/lib/db/queries";
import { canManageUsers, isSuperAdmin } from "~/lib/roles";
import { AdminLayout } from "~/components/admin/AdminLayout";
import { formatDate } from "~/lib/utils";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); if (!canManageUsers(appContext.user as never)) return redirect("/"); const url = new URL(request.url); const page = parseInt(url.searchParams.get("page") ?? "1"); const users = await getAllUsers(env.DB, page, 20); const roles = await getAllRoles(env.DB); return { appContext, users, roles }; };
export function meta() { return [{ title: "Usuarios — Admin" }]; }
export async function action({ request, context }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user || !canManageUsers(appContext.user as never)) return redirect("/"); const formData = await request.formData(); const userId = parseInt(formData.get("userId") as string); const action = formData.get("action") as string; if (action === "changeRole") { if (!isSuperAdmin(appContext.user as never)) return { error: "Solo super admin" }; await updateUserRole(env.DB, userId, parseInt(formData.get("roleId") as string)); return { success: "Rol actualizado" }; } if (action === "toggleStatus") { await updateUserStatus(env.DB, userId, formData.get("status") as string); return { success: "Estado actualizado" }; } return null; }
export default function AdminUsers({ loaderData, actionData }: Route.ComponentProps) { const { user, users, roles } = loaderData; const canChange = isSuperAdmin(user as never); return <AdminLayout user={user!} activeSection="users"><div><h1 className="text-2xl font-bold mb-6">Usuarios ({users.total})</h1>{actionData?.error && <div className="bg-red-50 border border-red-200 text-red-700 rounded-lg p-3 text-sm mb-4">{actionData.error}</div>}{actionData?.success && <div className="bg-green-50 border border-green-200 text-green-700 rounded-lg p-3 text-sm mb-4">{actionData.success}</div>}<div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-border"><tr className="text-left text-muted"><th className="p-3">Usuario</th><th className="p-3">Registro</th><th className="p-3">Estado</th><th className="p-3">Rol</th><th className="p-3">Acciones</th></tr></thead><tbody>{users.items.map((u) => <tr key={u.id} className="border-b border-border last:border-0"><td className="p-3"><p className="font-medium">{u.name}</p><p className="text-xs text-muted">{u.email}</p></td><td className="p-3 text-muted">{formatDate(u.created_at)}</td><td className="p-3"><span className={"badge " + u.status === "active" ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"}>{u.status}</span></td><td className="p-3">{canChange ? <form method="post" className="flex gap-1"><input type="hidden" name="action" value="changeRole" /><input type="hidden" name="userId" value={u.id} /><select name="roleId" defaultValue={u.role_id} className="input h-8 py-0 text-xs">{roles.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select><button type="submit" className="btn-primary h-8 px-2 text-xs">OK</button></form> : <span className="text-xs">{roles.find((r) => r.id === u.role_id)?.name}</span>}</td><td className="p-3">{u.id !== user!.id && <form method="post"><input type="hidden" name="action" value="toggleStatus" /><input type="hidden" name="userId" value={u.id} /><input type="hidden" name="status" value={u.status === "active" ? "suspended" : "active"} /><button type="submit" className="text-xs text-red-500">{u.status === "active" ? "Suspender" : "Activar"}</button></form>}</td></tr>)}</tbody></table></div></div></AdminLayout>; }
