import { redirect } from "react-router";
import { Link } from "react-router";
import type { Route } from "./+types/checkout";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getCartItems, createOrder, addOrderItem, clearCart, getAddressesByUser, createAuditLog } from "~/lib/db/queries";
import { formatPrice } from "~/lib/utils";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); const cartItems = await getCartItems(env.DB, appContext.user.id); if (cartItems.length === 0) return redirect("/carrito"); const addresses = await getAddressesByUser(env.DB, appContext.user.id); const subtotal = cartItems.reduce((s, i: any) => s + i.price * i.quantity, 0); const shipping = subtotal >= 50 ? 0 : 4.99; return { appContext, cartItems, addresses, subtotal, shipping, total: subtotal + shipping }; };
export function meta() { return [{ title: "Checkout — TiendaOnline" }]; }
export async function action({ request, context }: Route.ActionArgs) { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); if (!appContext.user) return redirect("/login"); const formData = await request.formData(); const cartItems = await getCartItems(env.DB, appContext.user.id); if (cartItems.length === 0) return redirect("/carrito"); const subtotal = cartItems.reduce((s, i: any) => s + i.price * i.quantity, 0); const shipping = subtotal >= 50 ? 0 : 4.99; const order = await createOrder(env.DB, { userId: appContext.user.id, total: subtotal + shipping, shippingAddress: formData.get("addressId") as string, paymentMethod: formData.get("paymentMethod") as string }); for (const item of cartItems as any[]) { await addOrderItem(env.DB, { orderId: order.id, productId: item.product_id, variantId: item.variant_id, productName: item.name, unitPrice: item.price, quantity: item.quantity, subtotal: item.price * item.quantity }); } await clearCart(env.DB, appContext.user.id); await createAuditLog(env.DB, { userId: appContext.user.id, action: "order_created", entityType: "order", entityId: order.id }); return redirect(`/cuenta/pedidos?new=${order.id}`); }
export default function Checkout({ loaderData }: Route.ComponentProps) {
  const { cartItems, addresses, subtotal, shipping, total } = loaderData;
  return (<div className="container-app py-8"><h1 className="text-2xl font-bold mb-6">Finalizar compra</h1><form method="post" className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-6"><div className="card p-6"><h2 className="font-bold mb-4">📍 Dirección</h2>{addresses.length === 0 ? <p className="text-muted text-sm">Sin direcciones. <Link to="/cuenta/direcciones" className="text-brand-600">Añadir</Link></p> : <div className="space-y-2">{addresses.map((a) => <label key={a.id} className="flex items-start gap-3 p-3 rounded-lg border border-border cursor-pointer"><input type="radio" name="addressId" value={a.id} defaultChecked={a.is_default === 1} className="mt-1" /><div className="text-sm"><p className="font-medium">{a.full_name}</p><p className="text-muted">{a.line1}, {a.city}</p></div></label>)}</div>}</div><div className="card p-6"><h2 className="font-bold mb-4">💳 Pago</h2><div className="space-y-2">{[{ id: "card", label: "Tarjeta", icon: "💳" }, { id: "paypal", label: "PayPal", icon: "🅿️" }, { id: "cod", label: "Contra reembolso", icon: "💵" }].map((m) => <label key={m.id} className="flex items-center gap-3 p-3 rounded-lg border border-border cursor-pointer"><input type="radio" name="paymentMethod" value={m.id} defaultChecked={m.id === "card"} /><span>{m.icon}</span><span className="text-sm font-medium">{m.label}</span></label>)}</div></div></div><div className="card p-6 h-fit"><h2 className="font-bold text-lg mb-4">Resumen</h2><div className="space-y-2 mb-4">{cartItems.map((i: any) => <div key={i.id} className="flex justify-between text-sm"><span className="text-muted">{i.name} × {i.quantity}</span><span>{formatPrice(i.price * i.quantity)}</span></div>)}</div><hr className="border-border mb-4" /><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted">Subtotal</span><span>{formatPrice(subtotal)}</span></div><div className="flex justify-between"><span className="text-muted">Envío</span><span>{shipping === 0 ? "Gratis" : formatPrice(shipping)}</span></div><hr className="border-border" /><div className="flex justify-between font-bold text-lg"><span>Total</span><span className="text-brand-600">{formatPrice(total)}</span></div></div><button type="submit" className="btn-primary w-full mt-4">✅ Confirmar</button></div></form></div>);
}
