import { Link, useFetcher } from "react-router";
import type { Route } from "./+types/view";
import type { Env } from "~/lib/types";
import { loadAppContext } from "~/lib/app-context";
import { getCartItems } from "~/lib/db/queries";
import { formatPrice } from "~/lib/utils";
export const loader = async ({ request, context }: Route.LoaderArgs) => { const env = (context as { cloudflare: { env: Env } }).cloudflare.env; const appContext = await loadAppContext(request, env); let cartItems: any[] = []; if (appContext.user) cartItems = await getCartItems(env.DB, appContext.user.id); const subtotal = cartItems.reduce((s, i) => s + i.price * i.quantity, 0); return { appContext, cartItems, subtotal }; };
export function meta() { return [{ title: "Carrito — TiendaOnline" }]; }
export default function CartView({ loaderData }: Route.ComponentProps) {
  const { cartItems, subtotal } = loaderData; const fetcher = useFetcher(); const shipping = subtotal >= 50 ? 0 : 4.99; const total = subtotal + shipping;
  if (!loaderData.appContext.user) return <div className="container-app py-16 text-center"><div className="card p-8"><h1 className="text-2xl font-bold mb-4">Inicia sesión</h1><Link to="/login" className="btn-primary">Login</Link></div></div>;
  if (cartItems.length === 0) return <div className="container-app py-16 text-center"><span className="text-6xl block mb-4">🛒</span><h1 className="text-2xl font-bold mb-4">Carrito vacío</h1><Link to="/productos" className="btn-primary">Ver productos</Link></div>;
  return (<div className="container-app py-8"><h1 className="text-2xl font-bold mb-6">Carrito ({cartItems.length})</h1><div className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-3">{cartItems.map((item) => <div key={item.id} className="card p-4 flex gap-4"><Link to={"/productos/" + item.slug} className="shrink-0"><div className="w-20 h-20 rounded-lg bg-muted/10 overflow-hidden"><img src="/images/placeholder.svg" alt={item.name} className="h-full w-full object-cover" /></div></Link><div className="flex-1"><Link to={"/productos/" + item.slug} className="font-medium text-sm hover:text-brand-600">{item.name}</Link><p className="text-lg font-bold text-brand-600 mt-1">{formatPrice(item.price)}</p><div className="flex items-center gap-3 mt-2"><fetcher.Form method="post" action="/api/cart/update" className="flex items-center gap-2"><input type="hidden" name="cartItemId" value={item.id} /><button type="submit" name="action" value="decrease" className="btn-secondary h-8 w-8 p-0">−</button><span className="text-sm w-8 text-center">{item.quantity}</span><button type="submit" name="action" value="increase" className="btn-secondary h-8 w-8 p-0">+</button></fetcher.Form><fetcher.Form method="post" action="/api/cart/remove"><input type="hidden" name="cartItemId" value={item.id} /><button type="submit" className="text-sm text-red-500">Eliminar</button></fetcher.Form></div></div><div className="text-right"><p className="font-bold">{formatPrice(item.price * item.quantity)}</p></div></div>)}</div><div className="card p-6 h-fit"><h2 className="font-bold text-lg mb-4">Resumen</h2><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted">Subtotal</span><span>{formatPrice(subtotal)}</span></div><div className="flex justify-between"><span className="text-muted">Envío</span><span>{shipping === 0 ? "Gratis" : formatPrice(shipping)}</span></div><hr className="border-border" /><div className="flex justify-between font-bold text-lg"><span>Total</span><span className="text-brand-600">{formatPrice(total)}</span></div></div><Link to="/checkout" className="btn-primary w-full mt-4">Pagar</Link></div></div></div>);
}
