import { createRequestHandler } from "@react-router/cloudflare";
// @ts-ignore - this file is generated by the build
import * as build from "../build/server/index.js";

export default {
  async fetch(request: Request, env: Record<string, unknown>): Promise<Response> {
    const handler = createRequestHandler(build, "production");
    return handler(request, { cloudflare: { env } } as any);
  },
} satisfies ExportedHandler<Record<string, unknown>>;
